import os,sys
import time
os.system('apt install termux-api')
number = int(input('Enter Your Number Fast : '))
ll = int(input('Enter Limit : '))
print('\nPlease Wait 5s for Starting')
time.sleep(2)
os.system('termux-sms-send -n {} You are so great fool😂. Ekhon bash kaw. 🤣🤣.'.format(number))
print('Sorry Brother')
os.system('termux-sms-send -n {} Ara Vai Aida Ki Hoytache 🤔.  Wait koro.'.format(number))
print('Sorry Brother')
os.system('termux-sms-send -n {} Ara Vai ar Ektu Wait Koro. 🤣🤣.'.format(number))
print('Sorry Brother')
os.system('termux-sms-send -n {} Sorry Vai Ar Message Dibo Na. 🤣🤣.'.format(number))
print('Sorry Brother')
os.system('termux-sms-send -n {} Ara Vai Off Koiro Na😂. Tumar Phone to Taka ache. 🤣🤣.'.format(number))
print('Sorry Brother')
os.system('termux-sms-send -n {} Sorry Sorry Bro..... .'.format(number))
print('Sorry Brother')
os.system('termux-sms-send -n {} Moja Korlam. Tumio moja koro.'.format(number))
print('Sorry Brother')
os.system('termux-sms-send -n {} Tumar Friend er Sathe.  Bye Bye Bye.'.format(number))
print('Sorry Brother')